<?php
return [
    // es indirizzo PREFERIBILMENTE INDIRIZZI NELLA VOSTR CITTA ENTRO 20-35km distanza l'uno dall'altro
    // (so che non serve l'array di array associativi ma è più ordinato visivamente per noi scriverli)
    /*
        vanno inseriti a mano inoltre lat e lon
        dovete fare una chiamata axios su postman del vostro indirizzo al tomtom con la vostra APIKEY
        indirizzo e APIKEY sono params della chiamata url di tomtom
        e nella risposta json avrete i campi latitudine e longitudine da inserire
        https://api.tomtom.com/search/2/geocode/INDIRIZZO.json?&key=KEiNGuhsySt5PgvkmCw7C9Sb5vGdacR6
        nella risposta json trovate 'position' e avete lat e lon
        in modo alternativo potete andare su laravel inserire indirizzo e andare nel db a ricavarvi lat e lon che usa la stessa funzione della chiamata a tomtom
    */
    // esempio, attenetevi ai tipi delle colonne nella tabella del db
    [
        'address' => 'via vittorio veneto ,roma',
        'lat' => '41.90709',
        'lon' => '12.48991',
        'cover_img'=> 'public/apt_img/',
        'name'=>'BELLA CASA',
        'bed'=>'12',
        'room' => '8',
        'bathroom'=>'3',
        'shared_bathroom'=>'', /*boolean 1 0 true false */
        'description'=>'affittami stronzo',
        'visible'=>'true', /*boolean 1 0 true false */
        'price'=>'199.99',/*decimal  */
        'square_meter'=>'',

    ],
    // 7 indirizzi STEFANO
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    // 7 indirizzi Ale M
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    // 7 indirizzi PIERPAOLO
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    //  7 indirizzi EROS
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    // 7 indirizzi ale ebr
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
];

// come fare il seedr in ApartmentSeeder quando è completo
/*
    
    
        $addresses =  config('apt_addresses');

        Schema::withoutForeignKeyConstraints(function(){
            Apartment::truncate();
        });

        foreach($singleAddress as $addresses) { 
            
            Apartment::create([
                'room' => $singleAddress['room'],
                'bed'  => $singleAddress['bed'],
                'bathroom' => $singleAddress['bathroom'],
                'shared_bathroom' => $singleAddress['shared_bathroom'],
                'address' => $singleAddress['address'],
                'lat' => $singleAddress['lat'],
                'lon' => $singleAddress['lon'],
                'visible' => $singleAddress['visible'],,
                'name' => $singleAddress['name'],,
                'price' => $singleAddress['price'],,
                'square_meter' => $singleAddress['square_meter'],,
                'description' => $singleAddress['description'],,
                'cover_img' => $singleAddress['cover_img'],
                'user_id' => rand(1, 2)
            ]);
        }
*/