<?php
return [

    // 7 indirizzi STEFANO
    [
        'address' => 'Vico di Pellicceria, 16124 Genova GE, Italia',
        'lat' => '44.4109216',
        'lon' => '8.9302048',
        'cover_img'=> 'public/apt_img/attico.centro.storico.webp',
        'name'=>'Attico esclusivo Centro Storico',
        'bed'=>2,
        'room' => 1,
        'bathroom'=>1,
        'shared_bathroom'=>0,
        'description'=> "Rilassati e ricaricati in quest'oasi di quiete ed eleganza. Attico lussuoso privato con terrazza e jacuzzi uso esclusivo affacciato sul museo di Pelliceria, a due passi dall'Acquario e dal Porto Antico nel cuore del Centro Storico di Genova.
        Appartamento nuovo arredato con ricercatezza e marchi importanti e dotato di ogni confort, il palazzo d'interesse storico-artistico è stato completamente ristrutturato ed è dotato di ascensore, palestra condominiale e zona relax",
        'visible'=>1,
        'price'=> 99,
        'square_meter'=> 150,

    ],
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    // 7 indirizzi Ale M
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    // 7 indirizzi PIERPAOLO
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    //  7 indirizzi EROS
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
    // 7 indirizzi ale ebr
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
   [
        'address' => '',
        'lat' => '',
        'lon' => '',
        'cover_img'=> 'public/img/apt_img/',
        'name'=>'',
        'bed'=>'',
        'room' => '',
        'bathroom'=>'',
        'shared_bathroom'=>'',
        'description'=>'',
        'visible'=>'',
        'price'=>'',
        'square_meter'=>'',

    ],
];

// come fare il seedr in ApartmentSeeder quando è completo
/*
    
    
        $addresses =  config('apt_addresses');

        Schema::withoutForeignKeyConstraints(function(){
            Apartment::truncate();
        });

        foreach($singleAddress as $addresses) { 
            
            Apartment::create([
                'room' => $singleAddress['room'],
                'bed'  => $singleAddress['bed'],
                'bathroom' => $singleAddress['bathroom'],
                'shared_bathroom' => $singleAddress['shared_bathroom'],
                'address' => $singleAddress['address'],
                'lat' => $singleAddress['lat'],
                'lon' => $singleAddress['lon'],
                'room' => $singleAddress['room']
                'visible' => $singleAddress['visible'],,
                'name' => $singleAddress['name'],,
                'price' => $singleAddress['price'],,
                'square_meter' => $singleAddress['square_meter'],,
                'description' => $singleAddress['description'],,
                'cover_img' => $singleAddress['cover_img'],
                'user_id' => rand(1, 2)
            ]);
        }
*/